spring:
  h2:
    console: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:C:\springframework\workspace\my-bulletin;
    username: root
    password: 9557  
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
